function M_sym = calc_M(in1)
%CALC_M
%    M_SYM = CALC_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Jun-2026 15:16:43

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = t2.*1.115625e-1;
M_sym = reshape([q2.*(-9.84236e-1)+q2.*sin(q3).*2.23125e-1+q2.^2.*(5.9e+1./2.0e+1)-t2.^2.*1.9918921875e-2+1.75862407115e-1,4.598e-3,0.0,4.598e-3,5.9e+1./2.0e+1,t3,0.0,t3,2.0423921875e-2],[3,3]);
