function C_sym = calc_C(in1,in2)
%CALC_C
%    C_SYM = CALC_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Jun-2026 15:16:43

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = sin(q3);
t4 = q2.*(5.9e+1./2.0e+1);
t5 = t3.*1.115625e-1;
t6 = q2.*t2.*1.115625e-1;
t9 = t2.*t3.*1.9918921875e-2;
t7 = t4+t5-4.92118e-1;
t10 = t6+t9;
t8 = dq1.*t7;
t11 = dq1.*t10;
C_sym = reshape([dq2.*t7+dq3.*t10,-t8,-t11,t8,0.0,0.0,t11,dq3.*t3.*(-1.115625e-1),0.0],[3,3]);
