function G_sym = calc_G(in1)
%CALC_G
%    G_SYM = CALC_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Jun-2026 15:16:43

q3 = in1(3,:);
G_sym = [0.0;0.0;sin(q3).*1.094428125];
